image: 192.168.89.128:90/library/docker:git

before_script:
  - docker login 192.168.89.128:90 -p gitLab12345 -u gitlab
  
stages:
  - build

job_build:
  stage: build
  script:
    - docker build -t 192.168.89.128:90/tct/centos-base-env .
    - docker push 192.168.89.128:90/tct/centos-base-env:latest
  only:
    - master
  tags:
    - shared-runner
